Php8.2
1ma/JsonRpc pull request #15
Opened 2023-04-21 11:18 UTC by o-perator

2023-04-24 13:53 UTC, jonwayne-tithely commented
Other than renaming the project in composer, these changes look like something that is needed. Is there a reason for closing it?

2023-04-25 06:09 UTC, o-perator commented
Hi)
When opening PR, I missed it, and instead of my fork I opened it to the main repository)
A little later I will issue a normal PR)

2023-04-25 21:43 UTC, 1ma requested changes

2023-04-25 21:43 UTC, 1ma commented on .gitignore
> +.idea
Remove IDE-specific .gitignore directive.

2023-04-25 21:43 UTC, 1ma commented
LGTM except for that little thing! Thanks for your contribution.

2023-04-26 06:04 UTC, o-perator commented on .gitignore
> +.idea
removed

2023-04-26 07:29 UTC, 1ma approved these changes

2023-04-26 07:30 UTC, merged

2023-04-26 08:13 UTC, 1ma commented
@o-perator @jonwayne-tithely tagged as 4.1.0